name: Verify the action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action
        with:
          MY_NAME: "Mona"
